use_frameworks!

target 'ActivityIndicator_Example' do
  pod 'ActivityIndicator', :path => '../'

  target 'ActivityIndicator_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
